plot_genotypes <- c("N2",
                    "WT",
                     "cest-2.1",
                     "tbh-1",
                    "tbh-1; cest-2.1",
                     "bas-1",
                    "bas-1; cest-2.1",
                    "tph-1",
                    "tph-1; cest-2.1",
                     "TIBR1",
                     "TIBR2",
                     "glo-1",
                     "fcmt-1",
                     "cat-1",
                     "cest-1.2")
